export const GET_EMPLOYEES_LOADING = 'GET_EMPLOYEES_LOADING;';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';
export const DELETE_EMPLOYEES_LOADING = 'DELETE_EMPLOYEES_LOADING;';
export const DELETE_EMPLOYEES_SUCCESS = 'DELETE_EMPLOYEES_SUCCESS';
export const DELETE_EMPLOYEES_ERROR = 'DELETE_EMPLOYEES_ERROR';
export const SET_MODAL_TITLE = 'SET_MODAL_TITLE';
export const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT';
