export const LOGIN_LOADING = 'LOGIN_LOADING';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const SET_LOGGED_OUT = 'SET_LOGGED_OUT';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
